BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'PAYMENT' (
    'USERNAME'    TEXT NOT NULL,
    'CAR_ID'    TEXT NOT NULL,
    'ORDER_DATETIME'    TEXT NOT NULL,
    'PAYMENT_DATETIME'    TEXT NOT NULL,
    'AMOUNT'    INTEGER NOT NULL,
    PRIMARY KEY('USERNAME','CAR_ID','ORDER_DATETIME','PAYMENT_DATETIME'),
    FOREIGN KEY('USERNAME') REFERENCES 'ORDERS'('USERNAME'),
    FOREIGN KEY('ORDER_DATETIME') REFERENCES 'ORDERS'('DATETIME'),
    FOREIGN KEY('CAR_ID') REFERENCES 'ORDERS'('CAR_ID')
);
CREATE TABLE IF NOT EXISTS 'CHARGES' (
  'UID'  INTEGER NOT NULL,
  'CAR_ID'  TEXT NOT NULL,
  'DATETIME'  TEXT NOT NULL,
  'STATUS'  TEXT NOT NULL,
  'CHARGING_TIME'  TEXT NOT NULL,
  'COST'  INTEGER NOT NULL,
  FOREIGN KEY('UID') REFERENCES 'CHARGING_STATIONS'('UID'),
  FOREIGN KEY('CAR_ID') REFERENCES 'CARS'('CAR_ID'),
  PRIMARY KEY('UID','CAR_ID','DATETIME')
);
CREATE TABLE IF NOT EXISTS 'ORDERS' (
    'USERNAME'    TEXT NOT NULL,
    'CAR_ID'    TEXT NOT NULL,
    'DATETIME'    TEXT NOT NULL,
    'FROM_'    TEXT NOT NULL,
    'TO_'    TEXT NOT NULL,
    'STATUS'    TEXT NOT NULL,
    'PRICE'    INTEGER NOT NULL,
    'TRAVELED_TO_CLIENT'    INTEGER NOT NULL,
    'DURATION'    TEXT NOT NULL,
    FOREIGN KEY('CAR_ID') REFERENCES 'CARS'('CAR_ID'),
    FOREIGN KEY('USERNAME') REFERENCES 'CUSTOMERS'('USERNAME'),
    PRIMARY KEY('USERNAME','CAR_ID','DATETIME')
);
CREATE TABLE IF NOT EXISTS 'REPAIRS' (
    'WID'    INTEGER NOT NULL,
    'CAR_ID'    TEXT NOT NULL,
    'DATETIME'    TEXT NOT NULL,
    'STATUS'    TEXT NOT NULL,
    'PRICE'    INTEGER NOT NULL,
    FOREIGN KEY('CAR_ID') REFERENCES 'CARS'('CAR_ID'),
    FOREIGN KEY('WID') REFERENCES 'WORKSHOPS'('WID'),
    PRIMARY KEY('WID','CAR_ID','DATETIME')
);
CREATE TABLE IF NOT EXISTS 'AVAILABLE_PARTS' (
    'NAME'    TEXT NOT NULL,
    'WID'    INTEGER NOT NULL,
    FOREIGN KEY('WID') REFERENCES 'WORKSHOPS'('WID'),
    FOREIGN KEY('NAME') REFERENCES 'CAR_PARTS'('NAME'),
    PRIMARY KEY('NAME','WID')
);
CREATE TABLE IF NOT EXISTS 'PARTS_FOR' (
    'NAME'    TEXT NOT NULL,
    'MODEL'    TEXT NOT NULL,
    FOREIGN KEY('MODEL') REFERENCES 'CAR_TYPES'('MODEL'),
    FOREIGN KEY('NAME') REFERENCES 'CAR_PARTS'('NAME'),
    PRIMARY KEY('NAME','MODEL')
);
CREATE TABLE IF NOT EXISTS 'CAN_PROVIDE' (
    'ID'    INTEGER NOT NULL,
    'NAME'    TEXT NOT NULL,
    FOREIGN KEY('ID') REFERENCES 'PARTS_PROVIDERS'('ID'),
    FOREIGN KEY('NAME') REFERENCES 'CAR_PARTS'('NAME'),
    PRIMARY KEY('ID','NAME')
);
CREATE TABLE IF NOT EXISTS 'SOCKETS' (
    'UID'    INTEGER NOT NULL,
    'PLUG_TYPE'    TEXT NOT NULL,
    'NUMBER'    INTEGER NOT NULL,
    FOREIGN KEY('UID') REFERENCES 'CHARGING_STATIONS'('UID'),
    PRIMARY KEY('PLUG_TYPE','UID')
);
CREATE TABLE IF NOT EXISTS 'CHARGING_STATIONS' (
    'UID'    INTEGER NOT NULL,
    'GPS_LOCATION'    TEXT NOT NULL,
    'CHARGING_COST'    TEXT NOT NULL,
    'CHARGING_TIME'    TEXT NOT NULL,
    PRIMARY KEY('UID')
);
CREATE TABLE IF NOT EXISTS 'CUSTOMERS' (
    'USERNAME'    TEXT NOT NULL,
    'EMAIL'    TEXT NOT NULL,
    'PHONE'    TEXT NOT NULL,
    'FULL_NAME'    TEXT NOT NULL,
    'COUNTRY'    TEXT NOT NULL,
    'CITY'    TEXT NOT NULL,
    'ZIP_CODE'    TEXT NOT NULL,
    PRIMARY KEY('USERNAME')
);
CREATE TABLE IF NOT EXISTS 'CARS' (
    'CAR_ID'    TEXT NOT NULL,
    'COLOR'    TEXT NOT NULL,
    'MODEL'    TEXT NOT NULL,
    FOREIGN KEY('MODEL') REFERENCES 'CAR_TYPES'('MODEL'),
    PRIMARY KEY('CAR_ID')
);
CREATE TABLE IF NOT EXISTS 'CAR_TYPES' (
    'MODEL'    TEXT NOT NULL,
    'PLUG_TYPE'    TEXT NOT NULL,
    PRIMARY KEY('MODEL')
);
CREATE TABLE IF NOT EXISTS 'WORKSHOPS' (
    'WID'    INTEGER NOT NULL,
    'GPS_LOCATION'    TEXT NOT NULL,
    'AVAILABILITY'    TEXT NOT NULL,
    PRIMARY KEY('WID')
);
CREATE TABLE IF NOT EXISTS 'CAR_PARTS' (
    'NAME'    TEXT NOT NULL,
    PRIMARY KEY('NAME')
);
CREATE TABLE IF NOT EXISTS 'PARTS_PROVIDERS' (
    'ID'    INTEGER NOT NULL,
    'ADRESS'    TEXT NOT NULL,
    'NAME'    TEXT NOT NULL,
    'PHONE'    TEXT NOT NULL,
    PRIMARY KEY('ID')
);
COMMIT;