# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.cars = QtWidgets.QWidget()
        self.cars.setObjectName("cars")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cars)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tblCars = QtWidgets.QTableWidget(self.cars)
        self.tblCars.setObjectName("tblCars")
        self.tblCars.setColumnCount(4)
        self.tblCars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tblCars, 0, 0, 1, 1)
        self.tabWidget.addTab(self.cars, "")
        self.customers = QtWidgets.QWidget()
        self.customers.setObjectName("customers")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.customers)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tblCustomers = QtWidgets.QTableWidget(self.customers)
        self.tblCustomers.setObjectName("tblCustomers")
        self.tblCustomers.setColumnCount(7)
        self.tblCustomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCustomers.setHorizontalHeaderItem(6, item)
        self.gridLayout_3.addWidget(self.tblCustomers, 0, 0, 1, 1)
        self.tabWidget.addTab(self.customers, "")
        self.order = QtWidgets.QWidget()
        self.order.setObjectName("order")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.order)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tblOrders = QtWidgets.QTableWidget(self.order)
        self.tblOrders.setObjectName("tblOrders")
        self.tblOrders.setColumnCount(9)
        self.tblOrders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrders.setHorizontalHeaderItem(8, item)
        self.gridLayout_4.addWidget(self.tblOrders, 0, 0, 1, 1)
        self.tabWidget.addTab(self.order, "")
        self.payment = QtWidgets.QWidget()
        self.payment.setObjectName("payment")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.payment)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tblPayment = QtWidgets.QTableWidget(self.payment)
        self.tblPayment.setObjectName("tblPayment")
        self.tblPayment.setColumnCount(5)
        self.tblPayment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tblPayment, 0, 0, 1, 1)
        self.tabWidget.addTab(self.payment, "")
        self.workshops = QtWidgets.QWidget()
        self.workshops.setObjectName("workshops")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.workshops)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tblWorkshop = QtWidgets.QTableWidget(self.workshops)
        self.tblWorkshop.setObjectName("tblWorkshop")
        self.tblWorkshop.setColumnCount(3)
        self.tblWorkshop.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblWorkshop.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWorkshop.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWorkshop.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.tblWorkshop, 0, 0, 1, 1)
        self.tabWidget.addTab(self.workshops, "")
        self.avParts = QtWidgets.QWidget()
        self.avParts.setObjectName("avParts")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.avParts)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tblParts = QtWidgets.QTableWidget(self.avParts)
        self.tblParts.setObjectName("tblParts")
        self.tblParts.setColumnCount(2)
        self.tblParts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblParts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblParts.setHorizontalHeaderItem(1, item)
        self.gridLayout_7.addWidget(self.tblParts, 0, 0, 1, 1)
        self.tabWidget.addTab(self.avParts, "")
        self.partProv = QtWidgets.QWidget()
        self.partProv.setObjectName("partProv")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.partProv)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tblProviders = QtWidgets.QTableWidget(self.partProv)
        self.tblProviders.setObjectName("tblProviders")
        self.tblProviders.setColumnCount(4)
        self.tblProviders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblProviders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProviders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProviders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProviders.setHorizontalHeaderItem(3, item)
        self.gridLayout_8.addWidget(self.tblProviders, 0, 0, 1, 1)
        self.tabWidget.addTab(self.partProv, "")
        self.canProvide = QtWidgets.QWidget()
        self.canProvide.setObjectName("canProvide")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.canProvide)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tblDetails = QtWidgets.QTableWidget(self.canProvide)
        self.tblDetails.setObjectName("tblDetails")
        self.tblDetails.setColumnCount(2)
        self.tblDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDetails.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.tblDetails, 0, 0, 1, 1)
        self.tabWidget.addTab(self.canProvide, "")
        self.repair = QtWidgets.QWidget()
        self.repair.setObjectName("repair")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.repair)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tblRepairs = QtWidgets.QTableWidget(self.repair)
        self.tblRepairs.setObjectName("tblRepairs")
        self.tblRepairs.setColumnCount(5)
        self.tblRepairs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblRepairs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRepairs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRepairs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRepairs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRepairs.setHorizontalHeaderItem(4, item)
        self.gridLayout_10.addWidget(self.tblRepairs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.repair, "")
        self.chargStat = QtWidgets.QWidget()
        self.chargStat.setObjectName("chargStat")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.chargStat)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tblChargSt = QtWidgets.QTableWidget(self.chargStat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.tblChargSt.sizePolicy().hasHeightForWidth())
        self.tblChargSt.setSizePolicy(sizePolicy)
        self.tblChargSt.setMinimumSize(QtCore.QSize(15, 10))
        self.tblChargSt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tblChargSt.setObjectName("tblChargSt")
        self.tblChargSt.setColumnCount(5)
        self.tblChargSt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblChargSt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChargSt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChargSt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChargSt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChargSt.setHorizontalHeaderItem(4, item)
        self.tblChargSt.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout_11.addWidget(self.tblChargSt, 0, 0, 1, 1)
        self.tabWidget.addTab(self.chargStat, "")
        self.charges = QtWidgets.QWidget()
        self.charges.setObjectName("charges")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.charges)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tblCharges = QtWidgets.QTableWidget(self.charges)
        self.tblCharges.setObjectName("tblCharges")
        self.tblCharges.setColumnCount(5)
        self.tblCharges.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCharges.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCharges.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCharges.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCharges.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCharges.setHorizontalHeaderItem(4, item)
        self.gridLayout_12.addWidget(self.tblCharges, 0, 0, 1, 1)
        self.tabWidget.addTab(self.charges, "")
        self.query = QtWidgets.QWidget()
        self.query.setObjectName("query")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.query)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnQ1 = QtWidgets.QPushButton(self.query)
        self.btnQ1.setObjectName("btnQ1")
        self.horizontalLayout.addWidget(self.btnQ1)
        self.btnQ2 = QtWidgets.QPushButton(self.query)
        self.btnQ2.setObjectName("btnQ2")
        self.horizontalLayout.addWidget(self.btnQ2)
        self.btnQ3 = QtWidgets.QPushButton(self.query)
        self.btnQ3.setObjectName("btnQ3")
        self.horizontalLayout.addWidget(self.btnQ3)
        self.btnQ4 = QtWidgets.QPushButton(self.query)
        self.btnQ4.setObjectName("btnQ4")
        self.horizontalLayout.addWidget(self.btnQ4)
        self.btnQ5 = QtWidgets.QPushButton(self.query)
        self.btnQ5.setObjectName("btnQ5")
        self.horizontalLayout.addWidget(self.btnQ5)
        self.btnQ6 = QtWidgets.QPushButton(self.query)
        self.btnQ6.setObjectName("btnQ6")
        self.horizontalLayout.addWidget(self.btnQ6)
        self.btnQ7 = QtWidgets.QPushButton(self.query)
        self.btnQ7.setObjectName("btnQ7")
        self.horizontalLayout.addWidget(self.btnQ7)
        self.btnQ8 = QtWidgets.QPushButton(self.query)
        self.btnQ8.setObjectName("btnQ8")
        self.horizontalLayout.addWidget(self.btnQ8)
        self.btnQ9 = QtWidgets.QPushButton(self.query)
        self.btnQ9.setObjectName("btnQ9")
        self.horizontalLayout.addWidget(self.btnQ9)
        self.btnQ10 = QtWidgets.QPushButton(self.query)
        self.btnQ10.setObjectName("btnQ10")
        self.horizontalLayout.addWidget(self.btnQ10)
        self.tabWidget.addTab(self.query, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tblCars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tblCars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tblCars.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plug type"))
        item = self.tblCars.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Colour"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cars), _translate("MainWindow", "Cars"))
        item = self.tblCustomers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tblCustomers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tblCustomers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.tblCustomers.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Full name"))
        item = self.tblCustomers.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Country"))
        item = self.tblCustomers.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "City"))
        item = self.tblCustomers.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Zip code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customers), _translate("MainWindow", "Customers"))
        item = self.tblOrders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tblOrders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tblOrders.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "From"))
        item = self.tblOrders.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "To"))
        item = self.tblOrders.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date & time"))
        item = self.tblOrders.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tblOrders.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Distance"))
        item = self.tblOrders.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tblOrders.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.order), _translate("MainWindow", "Orders"))
        item = self.tblPayment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date & time of order"))
        item = self.tblPayment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date and time of payment"))
        item = self.tblPayment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tblPayment.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tblPayment.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Car ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.payment), _translate("MainWindow", "Payment"))
        item = self.tblWorkshop.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tblWorkshop.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "GPD location"))
        item = self.tblWorkshop.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.workshops), _translate("MainWindow", "Workshops"))
        item = self.tblParts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tblParts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name of part"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.avParts), _translate("MainWindow", "Parts in workshops"))
        item = self.tblProviders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblProviders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tblProviders.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tblProviders.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.partProv), _translate("MainWindow", "Car parts providers"))
        item = self.tblDetails.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblDetails.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name of part"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canProvide), _translate("MainWindow", "Details"))
        item = self.tblRepairs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tblRepairs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tblRepairs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date & time"))
        item = self.tblRepairs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tblRepairs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repair), _translate("MainWindow", "Repairs"))
        item = self.tblChargSt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tblChargSt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sockets"))
        item = self.tblChargSt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Charging cost"))
        item = self.tblChargSt.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GPS location"))
        item = self.tblChargSt.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Charging time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chargStat), _translate("MainWindow", "Charging stations"))
        item = self.tblCharges.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tblCharges.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tblCharges.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date & time"))
        item = self.tblCharges.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Charging time"))
        item = self.tblCharges.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Charging cost"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.charges), _translate("MainWindow", "Charges"))
        self.btnQ1.setText(_translate("MainWindow", "Query 1"))
        self.btnQ2.setText(_translate("MainWindow", "Query 2"))
        self.btnQ3.setText(_translate("MainWindow", "Query 3"))
        self.btnQ4.setText(_translate("MainWindow", "Query 4"))
        self.btnQ5.setText(_translate("MainWindow", "Query 5"))
        self.btnQ6.setText(_translate("MainWindow", "Query 6"))
        self.btnQ7.setText(_translate("MainWindow", "Query 7"))
        self.btnQ8.setText(_translate("MainWindow", "Query 8"))
        self.btnQ9.setText(_translate("MainWindow", "Query 9"))
        self.btnQ10.setText(_translate("MainWindow", "Query 10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.query), _translate("MainWindow", "Queries"))

