# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.cars = QtWidgets.QWidget()
        self.cars.setObjectName("cars")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cars)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tblCars = QtWidgets.QTableWidget(self.cars)
        self.tblCars.setObjectName("tblCars")
        self.tblCars.setColumnCount(4)
        self.tblCars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCars.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tblCars, 0, 0, 1, 1)
        self.tabWidget.addTab(self.cars, "")
        self.customers = QtWidgets.QWidget()
        self.customers.setObjectName("customers")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.customers)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.customers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.customers, "")
        self.order = QtWidgets.QWidget()
        self.order.setObjectName("order")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.order)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.order)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.order, "")
        self.payment = QtWidgets.QWidget()
        self.payment.setObjectName("payment")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.payment)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.payment)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.payment, "")
        self.workshops = QtWidgets.QWidget()
        self.workshops.setObjectName("workshops")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.workshops)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.workshops)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.workshops, "")
        self.avParts = QtWidgets.QWidget()
        self.avParts.setObjectName("avParts")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.avParts)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.avParts)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.gridLayout_7.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.avParts, "")
        self.partProv = QtWidgets.QWidget()
        self.partProv.setObjectName("partProv")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.partProv)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.partProv)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.gridLayout_8.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.partProv, "")
        self.canProvide = QtWidgets.QWidget()
        self.canProvide.setObjectName("canProvide")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.canProvide)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.canProvide)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(2)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.tableWidget_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.canProvide, "")
        self.repair = QtWidgets.QWidget()
        self.repair.setObjectName("repair")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.repair)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.repair)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(5)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        self.gridLayout_10.addWidget(self.tableWidget_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.repair, "")
        self.chargStat = QtWidgets.QWidget()
        self.chargStat.setObjectName("chargStat")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.chargStat)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.chargStat)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(5)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(4, item)
        self.gridLayout_11.addWidget(self.tableWidget_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.chargStat, "")
        self.charges = QtWidgets.QWidget()
        self.charges.setObjectName("charges")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.charges)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.charges)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(4)
        self.tableWidget_10.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        self.gridLayout_12.addWidget(self.tableWidget_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.charges, "")
        self.query = QtWidgets.QWidget()
        self.query.setObjectName("query")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.query)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.query)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.query)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.query)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.query)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.query)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.query)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.query)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.query)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.query)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.query)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.tabWidget.addTab(self.query, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tblCars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tblCars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tblCars.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plug type"))
        item = self.tblCars.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Colour"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cars), _translate("MainWindow", "Cars"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Full name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Location of residence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customers), _translate("MainWindow", "Customers"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "To"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date & time"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Distance"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.order), _translate("MainWindow", "Orders"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date & time of order"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date and time of payment"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Car ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.payment), _translate("MainWindow", "Payment"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "GPD location"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.workshops), _translate("MainWindow", "Workshops"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name of part"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.avParts), _translate("MainWindow", "Parts in workshops"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.partProv), _translate("MainWindow", "Car parts providers"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name of part"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canProvide), _translate("MainWindow", "Details"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "WID"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date & time"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repair), _translate("MainWindow", "Repairs"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sockets"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Charging cost"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GPS location"))
        item = self.tableWidget_9.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Charging time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chargStat), _translate("MainWindow", "Charging stations"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Car ID"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Charging time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.charges), _translate("MainWindow", "Charges"))
        self.pushButton.setText(_translate("MainWindow", "Query 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Query 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Query 3"))
        self.pushButton_4.setText(_translate("MainWindow", "Query 4"))
        self.pushButton_5.setText(_translate("MainWindow", "Query 5"))
        self.pushButton_6.setText(_translate("MainWindow", "Query 6"))
        self.pushButton_7.setText(_translate("MainWindow", "Query 7"))
        self.pushButton_8.setText(_translate("MainWindow", "Query 8"))
        self.pushButton_9.setText(_translate("MainWindow", "Query 9"))
        self.pushButton_10.setText(_translate("MainWindow", "Query 10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.query), _translate("MainWindow", "Queries"))

